
Vagrant.configure(2) do |config| # 2 = version 2

# Configuration de la box utilisée pour les machines virtuelles
config.vm.box = "ubuntu/bionic64"
config.vm.box_url = "ubuntu/bionic64"


# Liste des serveurs avec leurs paramètres
NODES = [
  { :hostname => "jremyS", :ip => "192.168.56.10", :cpus => 1, :mem => 1024, :type => "master" },
  { :hostname => "jremySW", :ip => "192.168.56.11", :cpus => 1, :mem => 1024, :type => "worker" },
]


# Installation et configuration de chaque machine virtuelle
NODES.each do |node|
  config.vm.define node[:hostname] do |cfg|
    # Configuration spécifique de la machine virtuelle
    cfg.vm.hostname = node[:hostname]
    cfg.vm.network "private_network", ip: node[:ip]
    cfg.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--cpus", node[:cpus] ]
      v.customize [ "modifyvm", :id, "--memory", node[:mem] ]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] # active la résolution DNS pour la machine virtuelle en utilisant la fonctionnalité NAT (Network Address Translation) de VirtualBox. #ameliore les perfs non obligatoire
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"] # active le proxy DNS pour la machine virtuelle. 
      v.customize ["modifyvm", :id, "--name", node[:hostname] ]
    end

    # Ajout des entrées /etc/hosts pour chaque machine virtuelle
cfg.vm.synced_folder  ".", "/vagrant", type: "virtualbox"
cfg.vm.provision :shell, inline: <<-SHELL
# Activer l'authentification ChallengeResponse dans sshd_config
sudo sed -i 's/#ChallengeResponseAuthentication yes/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
sudo service ssh restart

# Exécuter le script "install_common.sh"
bash /vagrant/scripts/master.sh
SHELL
  end
end
end
